pipeline {
    // agent { // where the pipeline will run
    //     docker {
    //         image 'mcr.microsoft.com/playwright:v1.53.0-noble'
    //     }
    // }
    agent any // Use any available agent

    environment {
        BASE_URL_WEB = "https://barrigareact.wcaquino.me"
        BASE_URL_API = "https://barrigarest.wcaquino.me"
        USER = credentials("user_${params.ENVIRONMENT}")
        PASSWORD = credentials("password_${params.ENVIRONMENT}")
    }

    stages {

        stage('Print env variables') {
            steps {
                script {
                    echo "ENVIRONMENT: ${params.ENVIRONMENT}"
                    echo "BASE_URL_API: ${env.BASE_URL_API}"
                    echo "BASE_URL_WEB: ${env.BASE_URL_WEB}"
                    echo "USER: ${env.USER}"
                    echo "PASSWORD: ${env.PASSWORD}"
                }
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Static code analysis') {
            steps {
                script{
                    // TypeScript type checking
                    echo "Running TypeScript type checking..."
                    sh 'npx tsc --noEmit'
            
                    // ESLint checking
                    echo "Running ESLint checks..."
                    sh 'npx eslint "tests/**"'
                }
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                sh 'npx playwright install --with-deps chromium'  // Installs only Chromium (faster)
                // OR for all browsers:
                // sh 'npx playwright install'
            }
        }

        stage('Playright tests') {
            steps {
                sh 'npx playwright test tests/ui/e2e-tests/cross-env-tests.spec.ts'
            }
        }
    }
}
