pipeline {
    // agent { // where the pipeline will run
    //     docker {
    //         image 'mcr.microsoft.com/playwright:v1.53.0-noble'
    //     }
    // }
    agent any // Use any available agent

    // parameters {
    //     choice(
    //         name: 'ENVIRONMENT',
    //         choices: ['dev', 'prod'],
    //         description: 'Select environment'
    //     )
    // }

    environment {
        BASE_URL_WEB = "https://barrigareact.wcaquino.me"
        BASE_URL_API = "https://barrigarest.wcaquino.me"
        USER = credentials("user_${params.ENVIRONMENT}")
        PASSWORD = credentials("password_${params.ENVIRONMENT}")
    }

    stages {

        stage('Verify jenkins user') {
            steps {
                echo "Jenkins user: ${env.JENKINS_USER}"
                sh 'whoami' // Verify the Jenkins user
            }
        }

        stage('Print env variables') {
            steps {
                script {
                    echo "ENVIRONMENT: ${params.ENVIRONMENT}"
                    echo "BASE_URL_API: ${env.BASE_URL_API}"
                    echo "BASE_URL_WEB: ${env.BASE_URL_WEB}"
                    echo "USER: ${env.USER}"
                    echo "PASSWORD: ${env.PASSWORD}"
                }
            }
        }

        stage('Install Node.js') {
            steps {
                script {
                    // Install Node.js and npm (Linux/macOS)
                    sh '''
                        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                        sudo apt-get install -y nodejs
                        node --version  # Verify
                        npm --version
                    '''
               }
            }
        }    

        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('ESLint tests') {
            steps {
                sh 'npx eslint ./cypress --ext .js'
            }
        }

        stage('Playright tests') {
            steps {
                sh 'npx playwright test tests/ui/e2e-tests/cross-env-tests.spec.ts'
            }
        }
    }
}
