name: '1-basic-workflow-test'

on:
  workflow_dispatch:

env:
  BASE_URL_WEB: "https://barrigareact.wcaquino.me"
  BASE_URL_API: "https://barrigarest.wcaquino.me"
  USER: 'cypresstest@gmail.com'
  PASSWORD: 'cypress'

jobs:
  e2e-tests:
    # specify the environment to run the tests against
    runs-on: ubuntu-latest

    steps:
      #checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run ui-basic-tests