name: '3-basic-test-html-githubPages'

on:
  workflow_dispatch:

env:
  BASE_URL_WEB: "https://barrigareact.wcaquino.me"
  BASE_URL_API: "https://barrigarest.wcaquino.me"
  USER: 'cypresstest@gmail.com'
  PASSWORD: 'cypress'
  
permissions:
  pages: write
  id-token: write

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    # This is used to set the environment URL in the GitHub UI "e2e-tests" job box
    # it cannot be used together with the "environment" used to env variables

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Checkout code    
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Install dependencies    
      - name: Install dependencies
        run: npm ci

      # Install Playwright Browsers  
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      # Run Playwright tests  
      - name: Run Playwright tests
        run: npm run ui-basic-tests

      # upload html report results
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: test-results
          path: playwright-report/index.html  
          retention-days: 1

      # Configure GitHub Pages
      - uses: actions/configure-pages@v5 # upload test results

      # Upload the HTML report as a GitHub Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

      # Deploy the HTML report to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
