name: '4-env-variables-githubPages'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests against'
        required: true
        type: environment
        default: dev
  
permissions:
  pages: write
  id-token: write

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}   
      
    env:
      USER:  ${{ vars.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL_WEB: ${{ vars.BASE_URL_WEB }} 
      BASE_URL_API: ${{ vars.BASE_URL_API }}
      TEST_ENVIRONMENT: ${{ github.event.inputs.environment }}  #its necessary to specify the environment from where the env variables values are coming from
  
    steps:
      - name: check environment variables content
        run: | #it sets multiple lines for the echo command
          echo "Base URL web is $BASE_URL_WEB "
          echo "Base URL API is $BASE_URL_API}} "
          echo "Base USER is $USER "
          echo "Base environment is $ENVIRONMENT "         

      # Checkout code    
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Install dependencies    
      - name: Install dependencies
        run: npm ci

      # Install Playwright Browsers  
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      # Run Playwright tests  
      - name: Run Playwright tests
        run: npx playwright test tests/ui/e2e-tests/basic-tests.spec.ts

      # upload html report results
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
