name: 'E2E Tests'
#https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests against'
        required: true
        type: environment
        default: dev
        

jobs:
  option-example:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "input environment selected -> ${{ github.event.inputs.environment }}"

  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x    

      - name: Install dependencies
        run: npm ci

      - name: Check typescript
        run: npx tsc --noEmit

      - name: Check ESLint 
        run: npx eslint "tests/**"

  e2e-tests:
    needs: pre-check
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy

    steps:
      - name: read a variable
        run: echo "The USER is $USER and the base url is $BASE_URL_WEB and $TEST"
        env:
          USER:  ${{ vars.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL_WEB: ${{ vars.BASE_URL_WEB }} 
          BASE_URL_API: ${{ vars.BASE_URL_API }}
  
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test tests/ui/e2e-tests/cross-env-tests.spec.ts
        env:
          USER:  ${{ vars.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL_WEB: ${{ vars.BASE_URL_WEB }} 
          BASE_URL_API: ${{ vars.BASE_URL_API }}

      - uses: actions/upload-artifact@v4 # upload test results
        if: ${{ always() }}
        with:
          name: test-results
          path: playwright-report/

        # Deploy to GitHub Pages
        #https://github.com/actions/deploy-pages
        #https://github.com/leonardojorente/playwright-final-project/settings/pages -> enable pages on github
      - uses: actions/configure-pages@v5 # upload test results
        if: ${{ always() }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4