name: 'Cross Env E2E Tests'
#https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests against'
        required: true
        type: environment
        default: dev
        

jobs:
  option-example:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "input environment selected -> ${{ github.event.inputs.environment }}"

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install --with-deps
        env:
          HOME: /root
          USER:  ${{ env.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL_WEB: ${{ env.BASE_URL_WEB }} 
          BASE_URL_API: ${{ env.BASE_URL_API }}

      - name: Run Playwright tests
        run: npx playwright test tests/ui/e2e-tests/cross-env-tests.spec.ts